### ISSUE TITLE
デプロイの循環依存

### ISSUE THREAD

**Issue by wand2016** [wand2016/twitch-multi-player-reactive#6]
```yaml
  environment:
    CALLBACK_ENDPOINT:
      # callbackのAPI Gatewayのエンドポイント
      # .serverless/cloudformation-template-update-stack.json でexport定義されている
      Fn::ImportValue: sls-twitch-multi-player-${opt:stage,'dev'}-HttpApiUrl
```

- Lambda & API Gateway はenvironment依存
- しかし Lambda & API Gateway 一式ができないとFn::ImportValueが通らない
